export const FETCH_USER_DATA = 'FETCH_USER_DATA';

export const SELECTED_USER_INFORMATION = 'SELECTED_USER_INFORMATION';

export const SAVE_PROJECT = 'SAVE_PROJECT';

export const REMOVE_PROJECT = 'REMOVE_PROJECT';